# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml
github: https://github.com/howiefh

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- about_me
- category
- tagcloud
- archive
- calendar
- recent_posts
- duoshuo_recent_comments

# Miscellaneous
google_analytics: UA-40492061-1 
baidu_tongji: 56d2899c5e919fbf4a7b00de5d1c31dd 
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

# Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
# Scroll to top
go_top: true

# duoshuo
duoshuo_shortname: howiefh

# baidu share
baidushare: true

# blogroll
links:
- name: 404 page
  link: http://yibo.iyiyun.com/js/yibo404/key/1

# about me
about_me:
  title: ABOUT ME
  gravatar: howiefh@gmail.com
  avatar: http://fh-1.qiniudn.com/okal-eltocat.jpg
  texts:
  - Hi,I'm FengHao.
  - I'll share something interesting and my learning experience with you at this blog.
  - 前博客:<a href="http://hi.baidu.com/idea_star" target="_BLANK">百度空间</a>

# display updated
display_updated: true
